### ISSUE TITLE
[ADAP-1051] [Feature] Drop the temporary table upon a successful incremental refresh

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-bigquery#1036]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Background context

The current behavior is for `dbt-bigquery` to create a "temporary" table that expires after 12 hours when performing an incremental model update. This duration is hard-coded [here](https://github.com/dbt-labs/dbt-bigquery/blob/d29a230c2d35f3520396cc28c366a313e9cbe72a/dbt/adapters/bigquery/impl.py#L737).

### Describe the feature

Drop the temporary table upon a successful incremental refresh. There are other issues in this repo that speak to that approach. And using that approach would resolve this issue.

### Describe alternatives you've considered

An alternative approach would be to make the expiration duration configurable, particularly for incremental refreshes that occur more frequently than every 12 hours.

### Who will this benefit?

This benefits folks who refresh incremental models more frequently than every 12 hours. It would also benefit folks who are conscious of incremental spend as a result of these tables.

### Anything else?

See also: https://github.com/dbt-labs/dbt-bigquery/issues/1032

**Comment by dbeatty10** [comment]
> It may be worth considering dropping the temporary table upon a successful incremental refresh

From a user perspective, it would be awesome if dbt just drops temporary table like you mentioned.

@mikealfare What do you think about the following acceptance criteria?

### Proposed acceptance criteria

- When materializing a model, any intermediate database objects that are created along the way are dropped by the end of the materialization

We can re-use this acceptance criteria for other types of materializations as well (not just incremental models).

**Comment by dbeatty10** [comment]
### Questions about temp table vs. expiring permanent table vs. non-expiring permanent table

@mikealfare is there any way to create the intermediate table so that it is droppable?

Ideally, we'd avoid any intermediate objects persisting beyond the materialization (even if they they expire after X hours).

Is there something about adding an expiration to a permanent table that makes it harder to drop? Or are permanent tables inherently hard to drop in BigQuery? Is using a real BigQuery `temp` table an option?

### Current implementation

To the best that I can tell, we are not creating [temp](https://stackoverflow.com/questions/20673986/how-to-create-temporary-table-in-google-bigquery) tables. Rather, it looks like the intermediate table is a [permanent](https://cloud.google.com/bigquery/docs/writing-results#temporary_and_permanent_tables) table with an [expiration of 12 hours](https://github.com/dbt-labs/dbt-bigquery/blob/d29a230c2d35f3520396cc28c366a313e9cbe72a/dbt/adapters/bigquery/impl.py#L737) (like you mentioned). 

Side note: To make the code easier to read, it would be nice to replace references to "temp" or "temporary" to be either "intermediate" or "expiring" instead (to the extent either/or are accurate).

<details>
<summary>
Full code trace
</summary>

- [macros/materializations/incremental.sql#L131](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/include/bigquery/macros/materializations/incremental.sql#L131)
- [macros/materializations/incremental.sql#L26-L39](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/include/bigquery/macros/materializations/incremental.sql#L26-L39)
- [macros/adapters.sql#L29](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/include/bigquery/macros/adapters.sql#L29)
- [macros/relations/table/options.sql#L3](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/include/bigquery/macros/relations/table/options.sql#L3)
- [impl.py#L728](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/adapters/bigquery/impl.py#L728)
- [impl.py#L737](https://github.com/dbt-labs/dbt-bigquery/blob/d29a230c2d35f3520396cc28c366a313e9cbe72a/dbt/adapters/bigquery/impl.py#L737)
- [macros/relations/options.sql#L4](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/include/bigquery/macros/relations/options.sql#L4)

</details>

## Options for acceptance criteria

These are a mix of both behavior and implementation detail.

Option 1 includes the ideal state that all intermediate objects are dropped by the end of the materialization.

Options 2 and 3 explore what we could do if Option 1 isn't possible or practical for some reason.

### Option 1

1. Create an intermediate table using a permanent table without any expiration time.
1. Try to drop it at the end.
1. Block until time out, error, or success.
1. Raise error if any, otherwise continue.

Alternatively, use a (non-permanent) temporary table somehow.

### Option 2

1. Set expiration time for "temp" table to minimum time possible (60 minutes?).
1. Try to drop it at the end.
1. On error, make a log entry and continue anyway.
    - Make a log entry that the intermediate table will expire after X minutes.

### Option 3

Add detail to one of the GitHub issues that we tried dropping the "temp" table and it didn't work (for some unknown reason).

1. Set expiration time for the intermediate table to minimum time possible (60 minutes?).
1. Don't try to drop it at the end.
1. Make a log entry that the intermediate table will expire after X minutes.

**Comment by vinit2107** [comment]
@dbeatty10 @mikealfare
Can we also explore an option where the user can define which dataset the temp table gets materialized in? I understand the tables are already configured with an expiration policy, but if the user is refreshing the models at a cadence faster than the expiration, or the model takes a longer time to build, the table will be visible to users who aren't supposed to see it, which might cause some confusion (This will be true if the accesses are defined on the dataset level).

**Comment by dbeatty10** [comment]
Per @Fleid in an internal Slack conversation [here](https://dbt-labs.slack.com/archives/C05FWBP9X1U/p1705357788245269?thread_ts=1698154864.615099&cid=C05FWBP9X1U), we don't have the bandwidth to tackle this.

So labeling this as `help_wanted` for a motivated community member to take on.

Ideally, a PR that solves this would:
1. Implement Option 1 by dropping any intermediate tables during the materialization so they don't persist beyond
1. Be well-tested

See [here](https://github.com/dbt-labs/dbt-bigquery/issues/1032#issuecomment-1865190274) for an implementation idea.

And see [here](https://github.com/dbt-labs/dbt-bigquery/issues/1032#issuecomment-1865190106) for ideal acceptance criteria.

**Comment by vinit2107** [comment]
Hi @dbeatty10 , 
I have followed your suggestion [here](https://github.com/dbt-labs/dbt-bigquery/issues/1032#issuecomment-1865190274) and created a PR. I have also added a variable that can be defined in dbt_project.yaml `tmp_relation_dataset` where developers can define which dataset the tmp relations need to be materialized in. The default behavior remains the same, and the temp relations are dropped in both scenarios.
I have not updated the default expiration as `drop_relation` is dropping the table after execution.

Please let me know if you need me to update anything else. Thanks!!
