### ISSUE TITLE
“Syntax error: Unexpected keyword DECLARE” on valid query string

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-bigquery#1096]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In bigquery, I’m trying to read only the partitions not yet processed downstream. Bigquery is tricky for this because it’s implementation is … particular.

Avoiding a full column scan comes down to schema design (harder to change) or adding a predicate like where ingest_at > (select date_sub(current_timestamp(), interval 4 day)

I’ve tried writing jinja for this but it quickly got complex and testing that jinja is a whole new problem. 

Bigquery has a procedural language that enables:

```sql
declare most_recent_watermark 
default (
  select max(ingest_at)
  from {{ this }}
  where ingest_at > (
    select 
      date_sub(current_timestamp(),
      interval 4 day
    )
  )
)


select *
From {{ ref(“my_table”) }}
where 
  ingest_at > most_recent_watermark and
  ingest_at > (
    select 
      date_sub(current_timestamp(),
      interval 4 day
    )
  )
```

In the bigquery console, stubbing the jinja relation functions, this does exactly what I want. 

In a dbt model, it compiles but on run it throws an error:

```
syntax error: Unexpected keyword DECLARE at [15:1]
```

Is there a workaround?

### Expected Behavior

When I copy/paste the compiled query into the bigquery console it does exactly what I want. 

### Steps To Reproduce

```sql
declare most_recent_watermark 
default (
  select max(ingest_at)
  from {{ this }}
  where ingest_at > (
    select 
      date_sub(current_timestamp(),
      interval 4 day
    )
  )
)


select *
From {{ ref(“my_table”) }}
where 
  ingest_at > most_recent_watermark and
  ingest_at > (
    select 
      date_sub(current_timestamp(),
      interval 4 day
    )
  )
```

### Relevant log output

See above

### Environment

```markdown
- OS: windows
- Python: 3.10
- dbt-core: 1.7.7
- dbt-bigquery: 1.6.9
```

**Comment by dbeatty10** [comment]
Thanks for raising this @dbrtly!

### Returning the largest partition

Does https://github.com/dbt-labs/dbt-bigquery/issues/286 / https://github.com/dbt-labs/dbt-bigquery/pull/285 look like it would solve the problem you are going for?

### Using `sql_header`

In general, [`sql_header`](https://docs.getdbt.com/reference/resource-configs/sql_header) is how you can use `DECLARE`, like described [here](https://stackoverflow.com/a/74250350). But one limitation is that it can't use the `ref` or `source` macros.

Using `{{ this }}` [happens to work](https://github.com/dbt-labs/dbt-core/issues/2793#issuecomment-700722468) (as long as a [custom `generate_alias_name` isn't used](https://github.com/dbt-labs/dbt-core/issues/7151)).

Since I think `sql_header` allows you to use `DECLARE`, I'm going to close this issue as not needed. I've also opened up an issue to clarify the docs: https://github.com/dbt-labs/docs.getdbt.com/issues/4890

### Example

Something like this might work for you the way you hoped for:

```sql
{%- call set_sql_header(config) -%}

declare most_recent_watermark
default (
  select max(ingest_at)
  from {{ this }}
  where ingest_at > (
    select 
    date_sub(current_timestamp(),
    interval 4 day
    )
  )
);

{%- endcall %}

select *
from {{ ref("my_table") }}
where 
  ingest_at > most_recent_watermark and
  ingest_at > (
    select 
      date_sub(current_timestamp(),
      interval 4 day
    )
  )
```
