### ISSUE TITLE
Better exception message for when keyfile_json is used with model: service-account

### ISSUE THREAD

**Issue by Luttik** [dbt-labs/dbt-bigquery#128]
# Description
This one is somewhere in between a bug and a feature request.

Currently when you use a `keyfile_json` with the `method: service-account` you get the really unhelpfully error:

```
1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  expected str, bytes or os.PathLike object, not NoneType
```

After spending hours in the docs (searching for the source of this weird exception) I found that you should use the method `service-account-json` instead of `service-account` when you are using a `keyfile_json` instead of a `keyfile`. 

important sidenote: The naming here is really weird since in the `keyfile` option you are always using json, but in the keyfile_json option you don't need to necessarily input json, you can just use normal yaml (as the docs example does), and it is not a keyfile anymore either...

Also the error seems to indicate a connection error rather than a yaml schema issue (which this is).

# Solution
Therefore I'd suggest that the error for this should become way more description. Maybe something like:

```
1 check failed:
dbt was unable to parse the current profile.

You are using `model: service-account` in conjunction with `keyfile_json`.

You should either use
- `service-account` with `keyfile`
- or `service-account-json` with `keyfile_json`
```

Additionally one could add a comment to the docs that wants for this issue.

Like changing the line into
```
method: service-account-json  # warning don't use service-account in conjunction with keyfile_json.
```

This change is exceptionally important since
1. The difference is exceptionally easy to miss when reading the docs
2. The exception message is exceptionally opague.
3. The primary reason for using `keyfile_json` if modifying the project to use env variables rather than a key-file increasing the chance that the configuration is just copied and this change is missed.

**Comment by McKnight-42** [comment]
@Luttik Thank you for opening this issue, after looking into the code to find where we are defining this error message which i believe we are catching the exceptions here from any possible adapter connection attempt and just stringifying the exception thrown by the adapters.

As far as possible fixes or better hanlding we can do right now.
1. We could look here [connections.py](https://github.com/dbt-labs/dbt-bigquery/blob/5835c39b1e8b1d08229c3f40db6e7d2ec92a4bdf/dbt/adapters/bigquery/connections.py#L253-L267) and apply some conditional logic to raise an error on mismatch example something like
```keyfile = profile_credentials.keyfile
if not keyfile:
    raise DbtProfileError("'service-account' method requires 'keyfile'")
```
   This would prevent mismatches but stop workflow.

2. In same area change up logic so that the the type of `keyfile` provided internally matches to correct correct `service-account` type and throw out a warning pointing out mismatch. 

    this would internally fix and allow work to continue and alert there is a fix to be made.

3. Suggests docs change for more explicitly stated distinction between connection types. 

I think  2 would be the most long standing and fullest change we could make but icing on cake would be to also offer up a small note for a `docs` change by doing number 3 as well.

**Comment by lostmygithubaccount** [comment]
not stale, bot! it would have prevented this issue: https://github.com/dbt-labs/dbt-core/issues/5761 (or at least made it much more straightforward to triage...)

**Comment by Luttik** [comment]
@lostmygithubaccount I think the suggestion from @McKnight-42 is indeed quite easy to implement... I'd do it myself were it not that I know it would take me quite some time just setting up a proper development & testing structure based on this repo (I am missing a section in https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md for how to test it on an actual code base, I'd surely be able to figure it out, but it'd probably be quite a time-sink)

**Comment by Luttik** [comment]
I be4lieve this is still an issue?
