### ISSUE TITLE
[CT-335] Support for functions respecting require_partition_filter

### ISSUE THREAD

**Issue by nishantnathhoney** [dbt-labs/dbt-bigquery#131]
### Describe the feature
Tests should allow respecting tables specified with `require_partition_filter = true`

Onus of veracity of supplied arguments should be on user.

1.  An easy workaround is simply allowing users to specify the `<partitionField>`.
    - If `partition_field` is specified, append `WHERE <partitionField> IS NOT NULL`
    - If unspecified - no action taken
2. A customizable workaround is to allow users to specify a custom filter like `partition_filter = <partitionField> >= <date1> and <partionField> < <date2>` which can be appended during compilation step with `WHERE`.

Considering these tests would most likely never be run on specific date ranges only (option 2) is probably not a good idea.

### Describe alternatives you've considered
- Removing the `require_partition_filter = true` from source model is counterproductive

### Additional context
Originally raised as: https://github.com/dbt-labs/dbt-utils/issues/475
Google BigQuery specific feature

**Existing Compiled Output:**
```
with validation_errors as (

    select
        <col1>, <col2>
    from `project.dataset.table`
    group by <col1>, <col2>
    having count(*) > 1

)

select *
from validation_errors
```

**Proposed Compiled Output:**
```
with validation_errors as (

    select
        <col1>, <col2>
    from `project.dataset.table`
    WHERE <partitionField> IS NOT NULL    <----- New Condition added
    group by <col1>, <col2>
    having count(*) > 1

)

select *
from validation_errors
```

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by McKnight-42** [comment]
@nishantnathhoney so sorry for the long reply time, I have been gather context on this for a bit now and wanted to make sure we had a solid response to offer. 

from the context i've been able to find or learn from others in regards to `require_partition_filter`:
- In the case of a model configured with a partition + require_partition_filter, dbt does know that the table resulting from that model will be partitioned + require a partition filter
- By default, tests run against that model will fail because they don't specify a partition.

as @joellabes mentioned we have the current implementation of specifying `where` configs for every test. while the downside to the current method is a lot of repeated code

the choice of deciding a default action to take is a difficult choice overall different use cases would love to go with your solution and others would prefer to have protection of a test failure stopping a query if it could be costly.

a alternative solution was brought up. more of improving current solution. as a idea though. based on work from [#3256](https://github.com/dbt-labs/dbt-core/issues/3256) that might allow us to configure a bunch of tests at once without a lot of repetitive code.
Here are a few observations around this idea
- Configure where at the model level, have that where config inherited by all tests defined on that model
- Generic test definitions could more easily inspect the configs of the model they're defined on (including require_partition_by + partition_by), because they inherit those configs. That way, Nishant could define his own custom generic tests that follow his preferred behavior by default.

would love to hear your thoughts on this.
