### ISSUE TITLE
[CT-338] Add materialization Table Function

### ISSUE THREAD

**Issue by Jaxing** [dbt-labs/dbt-bigquery#132]
### Describe the feature
Be able to create table functions using dbt. Basically just create a macro for this that does something like

I guess the macro for creating table could be a guide, but add some more parameters.

### Describe alternatives you've considered
I think either this fits or it doens't :slightly_smiling_face: 

### Additional context
Since bigquery has released table functions which is basically a parameterized table

### Who will this benefit?
This is good if you want to parameterize your tables, e.g. if you want to be able to do some filtering based in datastudio parameters but also want to version control you queris.

### Are you interested in contributing this feature?
Yes but I would need some input on how. Found the materializations in https://github.com/dbt-labs/dbt-bigquery/tree/main/dbt/include/bigquery/macros/materializations but I'm not sure if the implementation is a straightforward as I see it.

**Comment by jtcohen6** [comment]
@Jaxing Thanks for opening, this is very cool!

"Table functions" in BigQuery ([docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/table-functions)) look a lot like "tabular functions" in Snowflake ([docs](https://docs.snowflake.com/en/developer-guide/udf/sql/udf-sql-tabular-functions.html)) which look a lot like "SQL functions returning `table`" in Postgres ([docs](https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-TABLE)). This feels less like a net-new thing in the world, and more like BQ extending support for a construct that's existed for some time in other databases.

In terms of how one might want to use this inside dbt: I'm not totally sure! For models with predictable structures, that only vary by a few inputs — such as the models templated by [the `dbtvault` package](https://hub.getdbt.com/datavault-uk/dbtvault/latest/)—the current art is to define macros that template a common model structure. Each model calls the macro, and provides just the arguments that differ for its instantiation. Should these models simply be calls to a table function (which take static inputs), rather than calls to a dbt macro? Preferences may vary here! I like the idea of seeing "source" and "compiled" SQL, a thing you obviously lose with table functions, but I imagine the latter might have some desirable performance characteristics.

Where it gets more interesting is thinking about _metrics_ queries. Could the dynamic queries templated by the [new `metrics` package](https://hub.getdbt.com/dbt-labs/metrics/latest/), which take time bounds and a set of dimensions as inputs, actually be a call to a reusable table function instead? Maybe! On databases that support table functions, we might want to consider them as a potential behind-the-scenes implementation—but certainly not require them across the board as the precondition to metrics support.

For now, you could use table functions in dbt + BigQuery the same way you can use non-tabular UDFs, or any other database feature that is SQL-addressable. I do think we want to eventually add first-class support for UDFs in dbt (https://github.com/dbt-labs/dbt-core/issues/136, https://github.com/dbt-labs/dbt-core/issues/3391). In the meantime, using existing constructs, I've seen two decent approaches, each with its own benefits and limitations:
- Wrap UDFs in macros, which get called during `on-run-start` hooks to ensure they're available
- Create a UDF "materialization," define UDFs as models (!), and `ref` them in downstream models (!!), which ensures that they are created in proper DAG order and the lineage is tracked in a straightforward manner

**Comment by Jaxing** [comment]
@jtcohen6 Thanks for your reply!

Yes I think I can find a work around for this using UDF, and metrics seems like it might handle the general use case :+1: 

> Should these models simply be calls to a table function (which take static inputs), rather than calls to a dbt macro?

In my use case these table functions would be used to parameterize a query in bigquery so that I can send a parameter from datastudio into a properly version controlled model. I.e. in datastudio I would have a custom query that looks something like this:

```
select * from my_table_function(@some_parameter)
```

Which would then allow the user of the dashboard to enter some value to modify the calculations being done (e.g. the size of a window that is applied).

> "Table functions" in BigQuery ([docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/table-functions)) look a lot like "tabular functions" in Snowflake ([docs](https://docs.snowflake.com/en/developer-guide/udf/sql/udf-sql-tabular-functions.html)) which look a lot like "SQL functions returning table" in Postgres ([docs](https://www.postgresql.org/docs/current/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-TABLE)). This feels less like a net-new thing in the world, and more like BQ extending support for a construct that's existed for some time in other databases.

Yeah maybe this is more general then the dbt-bigquery lib and should be moved to dbt-core?

**Comment by AdeelK93** [comment]
This would be a really great feature to have, so that we can parameterize the views we create at runtime. How do we reopen this?
The linked/mentioned issue is different and more complex to implement

**Comment by arthurreys** [comment]
Do we have any updates on this? I have the same use case where I want to versionate tables that depend on user inputs in a DataStudio dashboard. It would be awesome to have the possibility to create table functions via dbt!

**Comment by amirjalali1** [comment]
@Jaxing, did you find a workaround?

Is there any update on this?

**Comment by rynmccrmck** [comment]
Looks like there is still ongoing discussion about how to best incorporate this into dbt proper, we added custom materialization in meantime ([gist](https://gist.github.com/rynmccrmck/995e0b0f0db37c049222da5e0854593b)).
