### ISSUE TITLE
[CT-365] DBT Queries retries when hit with "Resources exceeded" error

### ISSUE THREAD

**Issue by nishantnathhoney** [dbt-labs/dbt-bigquery#141]
### Describe the feature
DBT queries on Google BigQuery follows the retries arg (default = 5) & retries queries which get "Resources exceeded" error
Queries which receive the error are unlikely to succeed & should either be not retried or user should be given an option to opt-out of retries for specific errors

### Describe alternatives you've considered
Reducing retries param will lead to other transient glitches not getting retried

### Additional context
Google BigQuery specific behavior

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by jtcohen6** [comment]
@nishantnathhoney Thanks for opening!

You're right, we're retrying on just about all BigQuery errors, both transient and otherwise:

https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/adapters/bigquery/connections.py#L51-L56

After taking a look through the code and [Google's `Retry` docs](https://googleapis.dev/python/google-api-core/latest/retry.html), it's clear that this part of the code could use a light refactor. Currently, we're using the `retry_target` method, and plumbing through its arguments ourselves. As the docs say:

> This is the lowest-level retry helper. Generally, you’ll use the higher-level retry helper [Retry](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry).

That higher-level `Retry` decorator incorporates Google's own `if_transient_error` conditional check:

> By default, this decorator will retry transient API errors (see [if_transient_error()](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.if_transient_error)).

At risk of confusing everyone (I got a bit confused myself), there are two angles into this. On the one hand, each `client` method has its own `retry` configuration. We're not overriding these today, Google advises against doing it, and I don't think we should start. On the other hand, specific methods are being passed today into a generalized retry method, and we could use Google's recommended decorator instead.

### Per-method retry

Google's [docs on the BigQuery client](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.retry.DEFAULT_RETRY.html#google-cloud-bigquery-retry-default-retry) mention that:
 
> Any method with a retry parameter will be retried automatically, with reasonable defaults.

We call lots of these methods: `client.query`, `client.create_dataset`, `client.get_table`, etc. Each of them is likely to have its own defaults. For instance, [the `query` method] has arguments for both `retry` and `job_retry` (https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.query):

> retry (Optional[[google.api_core.retry.Retry](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry)]) – How to retry the RPC. This only applies to making RPC calls. It isn’t used to retry failed jobs. This has a reasonable default that should only be overridden with care.
> job_retry (Optional[[google.api_core.retry.Retry](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry)]) – How to retry failed jobs. The default retries rate-limit-exceeded errors. Passing None disables job retry. Not all jobs can be retried. If job_id is provided, then the job returned by the query will not be retryable, and an exception will be raised if a non-None (and non-default) value for job_retry is also provided. Note that errors aren’t detected until result() is called on the job returned. The job_retry specified here becomes the default job_retry for result(), where it can also be specified.

We don't pass or override either of those arguments, so we're using the default values for both.

### Generalized retry

Many of these methods we also pass into centralized a `_retry_and_handle` method, which operates on the low-level `retry_target` method and implements our own (naive) retry logic. I think we should make these changes:
- Switch to using the higher-level `Retry` decorator. This uses Google's own definition of which errors are likely to succeed on retry. It also uses exponential backoff, up to maximum number of seconds, which is smarter than what our own `_ErrorCounter` logic is doing (retry every second, up to X number of times, configured by `job_retries`).
- It looks like the highest-level `Retry` object accepts a `deadline` argument, for which we can pass in the user-configured `job_retry_deadline_seconds`. I don't think that `job_retries` would take effect by default.
- We should add a new config, `retry_all`, which is comparable to the configs supported by [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/ae31719cb0c575460e647071e464f8e7344749ec/dbt/adapters/snowflake/connections.py#L62) + [dbt-spark](https://github.com/dbt-labs/dbt-spark/blob/fbf9abe397abd11baab6dfa7a903346774fec345/dbt/adapters/spark/connections.py#L79). This would offer backwards compatibility for the current naive/default behavior, and basically just pass `predicate=True` into the `Retry` decorator, until the number of retries (`job_retries`) or maximum timeout is reached.

https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/adapters/bigquery/connections.py#L595-L602

Some pseudo-code to give the idea:
```python
with self.exception_handler(msg):
    # legacy approach — backwards compatibility
    if self.get_job_retries(conn) and self.get_retry_all(conn):
       return retry.retry_target(
            target=fn,
            predicate=_ErrorCounter(self.get_job_retries(conn)).count_error,
            sleep_generator=self._retry_generator(),
            deadline=self.get_job_retry_deadline_seconds(conn),
            on_error=reopen_conn_on_error,
        )
    # better approach using higher-level Google Retry decorator
    else:
        @retry.Retry(deadline=self.get_job_retry_deadline_seconds(conn))
        return fn()
```

Is that something that you or another community member might be interested in working more on?

**Comment by dataders** [comment]
@nathaniel-may would #229 address in some way?

**Comment by nathaniel-may** [comment]
@dataders as long as we remove the old retry logic as well, my understanding is it would resolve this issue.
