### ISSUE TITLE
[CT-535] To use BigQuery TEMP table instead of native interim one for "insert_overwrite" strategy

### ISSUE THREAD

**Issue by xemuliam** [dbt-labs/dbt-bigquery#163]
### Describe the feature
Currently, when DBT performs `insert_overwrite` strategy, it creates native interim table (with 12h expiration) within the same dataset as target table. 

### Describe alternatives you've considered
Whereas `insert_overwrite` strategy implemented as single BigQuery script, it looks more relevant to use real BigQuery temporary table via `create or replace temp table` statement. It will let keep clear target dataset, decrease complexity of model resource graph (table name can be constant cos BigQuery will just use it as postfix for under-the-hood script related dataset) and will be under native BigQuery temp tables expiration management.

### Additional context
Additional impact on different macros (e.g.  snapshot etc.) should be additionally investigated to avoid unexpected behaviour.

### Are you interested in contributing this feature?
Yes, I'm in.

**Comment by xemuliam** [comment]
^ ^ ^ ^ ^
@jtcohen6

**Comment by jtcohen6** [comment]
Thanks for opening @xemuliam!

For context, [BigQuery only supports _real_ temporary tables within the context of a multi-statement query](https://cloud.google.com/bigquery/docs/multi-statement-queries#temporary_tables) ("scripting"). This makes sense, since BQ otherwise doesn't have a notion of sessions or transactions. The temp table naturally expires at the end of the script.

Given that limitation, dbt creates "fake" temp tables when the `create_table_as()` macro is called with `temporary=True. These are real permanent tables that are set to expire after 12 hours:

https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/adapters/bigquery/impl.py#L711-L713

When enough weird edge cases collide, it can result in an issue like https://github.com/dbt-labs/dbt-bigquery/issues/154.

There are three cases I'm aware of in which dbt creates "temp" tables on BigQuery:
1. Incremental models with `insert_overwrite` strategy + `on_schema_change = 'ignore'`. dbt uses a real script (multi-statement query for this); [the "temp" table is created as part of the script](https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/include/bigquery/macros/materializations/incremental.sql#L70-L71), and this could be a _real_ temp table without any other changes. We could also then remove the cleanup in [step 4](https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/include/bigquery/macros/materializations/incremental.sql#L90-L91).
2. Incremental models with `insert_overwrite` strategy + an "active" mode of `on_schema_change` — [the "temp" table must be created earlier](https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/include/bigquery/macros/materializations/incremental.sql#L175-L179), in order to assess and handle column schema changes. Those schema changes _could_ move into the 
3. Snapshots (BigQuery uses the core default materialization), which call [`build_snapshot_staging_table`](https://github.com/dbt-labs/dbt-core/blob/6267572ba764724c01386f5b768763aa5711f228/core/dbt/include/global_project/macros/materializations/snapshots/helpers.sql#L176-L178) in order to assess and handle column schema changes before running the atomic `merge`.

In an ideal world, `dbt-bigquery` would use scripts for all of those, including the column schema processing (`alter` statements) needed by 2 + 3, so that all of them could use "real" temp tables. That would be a much bigger lift, and it would require us to either duplicate or significantly refactor a lot of macro code from `dbt-core`.

In the meantime, let's find a non-invasive way to use a real temp table in the first scenario. We need some way to plumb through a new conditional argument, "real" temp table vs. fake-temp / "interim" table, and to make that intervention as surgically as possible.

I think there are two potential approaches:
1. A totally separate macro, `create_temp_table_as`. This would make sense if the arguments and options of `create_table_as` don't make much sense, and it's not a huge duplication of SQL between them.
2. If we're creating the temp table within the script, adjust `tmp_relation` to set its project/database + dataset/schema to `None`. (Temp tables should have identifiers only.) Then, in [`bigquery__create_table_as`](https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/include/bigquery/macros/adapters.sql#L44-L61), add some logic that checks for whether `temporary=True` and the project/database + dataset/schema are `None`. If so, `create temp table {{ tmp_relation.identifier }}`.

Curious to hear which of those resonates with you more.
