### ISSUE TITLE
[CT-766] [CT-761] [Bug] Truncate any labels from query-comment if >63 characters

### ISSUE THREAD

**Issue by amirbtb** [dbt-labs/dbt-bigquery#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't run dbt generic tests because the job label is too long (over 63 characters).

### Expected Behavior

The dbt generic test run without warning about the length of the tests.

### Steps To Reproduce

1. In a dockerized vscode environment
2. The sources are staged in a dataset named `stg` using [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) and they are defined in `stg.yml`. My project name is `dataplatform` (defined in `dbt_project.yml`), I defined a `unique` test on a column named `account_number` inside a source named `vendors`.
3. I run `dbt test`.
4. I am getting the following error : 
```
17:56:43  Runtime Error in test source_unique_stg_vendors_accountnumber (models/stg.yml)
17:56:43    Job label length 68 is greater than length limit: 63
17:56:43    Current sanitized label: test_dataplatform_source_unique_stg_vendors_accountnumber_45d7e27f34
```
I can't control the length of the job label. The only parameter I can change is the name of the project `dataplatform` but it's a quick fix and I need to be sure that I won't have this problem with column name slightly longer.

### Environment

```markdown
- OS: Ubuntu
- Python: 3.8.10
- dbt: 1.1.1
- dbt-bigquery: 1.1
```

### What database are you using dbt with?

bigquery

**Comment by amirbtb** [comment]
Hello @ChenyuLInx thank you for your quick reply 🙏 !

Let me know if I can be of any help.

**Comment by leahwicz** [comment]
@amirbtb this is a requirement set by BigQuery that `dbt` doesn't have control over. We just bumble up a nice error message to make it clear what is happening. You can find more info in the BigQuery docs about it [here](https://cloud.google.com/blog/products/gcp/labelling-and-grouping-your-google-cloud-platform-resources). 

I did open up a [PR to add to our internal docs](https://github.com/dbt-labs/docs.getdbt.com/pull/1631) to clarify that this is a BigQuery limitation though in case anyone else hits this and is wondering why the limitation exists.

**Comment by jtcohen6** [comment]
@amirbtb Sorry, I misunderstood this issue when we took a look at it earlier!

It sounds like you have `job-label` enabled for `query-comment` (https://docs.getdbt.com/reference/project-configs/query-comment) — is that right?

In which case, dbt is trying to turn the query comment dictionary into a set of labels, and it doesn't properly truncate any labels which are >63 characters if `json.loads(comment)` is successful. The logic for that is here:

https://github.com/dbt-labs/dbt-bigquery/blob/5e5437610482e83d4790085ef4deb35b9726ede9/dbt/adapters/bigquery/connections.py#L625-L633

I'm going to reopen this one, and mark it a `good_first_issue`, since I think it should be fairly straightforward to add a truncation step to the JSON-ified `comment`.

**Comment by amirbtb** [comment]
@jtcohen6 pardon me I forget to mention it, but indeed, I  have `job-label` enabled for `query-comment`. I tried to disable it on a test branch/environment and the tests run correctly. Now we know why experience this issue 😅 . 
For the moment we will disable `job-label` for `query-comment` on our test environments while keeping it in our prod environments (we are using them for audit purposes). 
Thank you for your prompt help 🙏🏽

**Comment by jtcohen6** [comment]
Marking this a `good_first_issue`. I think the right move is for dbt to _truncate_ the sanitized label, rather than raising an error, when it's being passed the dictionary returned by `json.loads(comment)`. I could see an argument for truncating rather than raising _all_ the time, even in cases where users are passing explicit strings as the `query-comment`.

https://github.com/dbt-labs/dbt-bigquery/blob/5e5437610482e83d4790085ef4deb35b9726ede9/dbt/adapters/bigquery/connections.py#L674-L687
