### ISSUE TITLE
[CT-976] [Feature] Parity on create_table_as for python and SQL model

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-bigquery#247]
### Describe the feature
[bigquery__create_table_as](https://github.com/dbt-labs/dbt-bigquery/blob/55bbd3d5a0760a66b01424c0a0884e6161b71b0e/dbt/include/bigquery/macros/adapters.sql#L44) macro support options like `partition_by`, `clustered_by`.

We should reach parity for this in python models where possible and raise a clear error when running with options that is not supported.

**Comment by griffinator76** [comment]
We ran into this issue while trying to implement python models on Bigquery. Specifically we found that partitioning config was ignored by python models so that the resulting tables in BQ were not partitioned. Querying unpartitioned tables in BQ can be really inefficient as there is no opportunity for partition pruning, resulting in expensive full table scans.

**Comment by dbeatty10** [comment]
Thanks for sharing your desire for this feature @griffinator76!

This just got re-opened in https://github.com/dbt-labs/dbt-bigquery/issues/680, so you may want to subscribe to that one.
