### ISSUE TITLE
Remove / reduce downtime when running full refresh

### ISSUE THREAD

**Issue by alepuccetti** [dbt-labs/dbt-bigquery#26]
### Describe the feature
Change the full refresh behaviour for BigQuery (or at least make it configurable).

Current behaviour:
1. Delete model destination table.
2. Run `create or replace` statement.

Proposed behaviour:

1. Create the full refreshed model in a temporary table (e.g. `model_table_name__tmp`).
2. Delete the `model_table_name` if full refresh is successful.
3. Copy `model_table_name__tmp` to `model_table_name`
4. Delete `model_table_name__tmp`

This solution has two advantages:
1. In case the query create or replace query fails the original table is still present.
2. Minimize downtime to just the time between the deletion and the copy instead of the time to run the query, which could be several minutes or even hours.

### Describe alternatives you've considered
No alternative solution found.

### Additional context
I am using BigQuery, not sure if could be extended to other.

### Who will this benefit?
Anyone that needs to run very big full refresh. This issue effects them linearly with the query execution time.
The solution reduces to the copy time, usually much faster than query execution for complex queries.

### Are you interested in contributing this feature?
With some guidance.

**Comment by gareginordyan** [comment]
Following this thread!

**Comment by gareginordyan** [comment]
#if the partition/cluster config has changed (between the existing table and the current model / new table to be built), so instead dbt "hard refreshes" the existing table

@jtcohen6 this was some time ago, but if I remember correctly, in our case our cluster/partition keys had not been changing and we were still having this downtime on a regular basis.

**Comment by gareginordyan** [comment]
@bcolbert978 I can't seen to find it in slack, but if you by any chance have the model config handy please paste here

**Comment by balazs-mate** [comment]
@gareginordyan : we had our fair share of problems with strange hard refreshes on non-incremental but partitioned and clustered tables. It all came down to the fact that we were using the `cluster_by: "column_a,column_b" ` syntax instead of the documented `cluster_by = ["column_a", "column_b"],` syntax and when dbt was checking if the table is replaceable or not, it always came back with False since `["column_a,column_b"]` does not equal `["column_a", "column_b"]`. https://github.com/dbt-labs/dbt-bigquery/blob/07bc1442c2e0711822983999b18d68ccd029cd41/dbt/adapters/bigquery/impl.py#L532

**Comment by bcolbert978** [comment]
@gareginordyan yes tracked it down - and @balazs-mate it was just as you describe with models materialized as `table` (so non-incremental and not full-refresh specific) and tables that were both partitioned and clustered (with a complex, four-column clustering scheme). We did not have the same syntax issues you describe, though. 

Example of the config causing issues:
```
{{
  config(
    schema='transforms_bi',
    partition_by={'field': 'date', 'granularity': 'day'},
    cluster_by = ['sf_account_id', 'fivetran_account_id', '`group`', 'integration',],
    materialized='table'
  )
}}
```

We were able to resolve the downtime issue by removing partitioning and dropping our clustering scheme to two columns:
```
{{
  config(
    schema='transforms_bi',
    cluster_by = ['sf_account_id', 'date'],
    materialized='table'
  )
}}
```
which led us to believe that the downtime issue was related to the way dbt and/or BigQuery was handling creating the partitioning - the raw downtime (as measured by the slot time consumed by the new version) was lower but not significantly lower. We now favor clustering over partitioning in nearly all cases and haven't seen these issues since.

This was all back in October 2021, running dbt version 0.19.1.

**Comment by OmarArain** [comment]
I'm seeing a similar issue.  I am materializing a BigQuery table that is partitioned and clustered - I run dbt run --select my_table every 15 minutes, and the downstream consumers report periodic downtime with errors like `Not found: Table my_table was not found in location US`.
