### ISSUE TITLE
[CT-1009] [CT-1008] [Bug] Catalog query regex is too aggressive at detecting sharded tables

### ISSUE THREAD

**Issue by adamcunnington-mlg** [dbt-labs/dbt-bigquery#260]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The following applies to BigQuery (not tested with other adapters):

If you define a source table where the underlying relation is a view, dbt cloud successfully "links" it to that relation and shows complete information; details, columns, sample SQL etc. Fantastic!

However, if the source table's underlying relation a table, it does not link. dbt Cloud docs do not show the relation nor (presumably therefore) the columns or a column list in the sample sql.

The ONLY thing different is the fact that one is a BQ view (works) and one is a BQ table (does not work).

See various screenshots.
![image](https://user-images.githubusercontent.com/93528462/183494939-48bc2147-1090-433d-b068-776259aaf07c.png)
![image](https://user-images.githubusercontent.com/93528462/183494989-8154b49f-6cfd-4b94-adb4-329e4d14bbb7.png)
![image](https://user-images.githubusercontent.com/93528462/183495072-5d471382-c410-4825-b3d5-662dded50f25.png)
![image](https://user-images.githubusercontent.com/93528462/183495438-9d8929fd-24dd-4d9f-9154-6f60a77bcc20.png)

### Expected Behavior

I expect that the table is successfully linked and all metadata is pulled back, just like when the source's underlying relation is a view.

### Steps To Reproduce

As above.

### Relevant log output

```shell
n/a
```

### Environment

```markdown
dbt: 1.2
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

n/a

**Comment by jtcohen6** [comment]
@adamcunnington-mlg This is an interesting one! I've transferred to `dbt-bigquery`, since this is where the relevant code lives, and would need updating.

Here's the relevant spot in the "catalog" query that dbt uses to fill out `catalog.json` during `docs generate`, and then power the docs site:

https://github.com/dbt-labs/dbt-bigquery/blob/764f5fe6370f9f7ed941a387104f57207dd562c6/dbt/include/bigquery/macros/catalog.sql#L26-L28

If the table's name ends in numbers and underscores, dbt considers it to be a "shard" from a date-sharded table ([docs](https://cloud.google.com/bigquery/docs/partitioned-tables#dt_partition_shard)). In that case, rather than catalog it as its own individual table, it will aggregate statistics about all date shards, and store them all under the "base" name.

In the case of your models, the "base" name it detects is (e.g.) `STD_MOBILITY_INDEXED_20220519163648` &rarr; `STD_MOBILITY_INDEXED`. So, if you were to check into the contents of `catalog.json`, you should see information available under `STD_MOBILITY_INDEXED`.

This doesn't happen when the model is materialized as a view, because views can't be sharded, and so dbt's catalog query doesn't include that regex check.

**Is dbt doing the wrong thing here?** I don't think so. Date-sharded tables is an older BigQuery feature, but some people do still seem to use it. This logic prevents us from blowing up the catalog with one entry per shard in tables that might have thousands.

What I do think we need is to document that this behavior exists, for users deciding how to name their dbt models on BigQuery. If you just add an alphabetic suffix to your model name, I think the issue would go away: `STD_MOBILITY_INDEXED_20220519163648_z`. Could you give that a try, as a way of confirming?

**Comment by adamcunnington-mlg** [comment]
Ah, thanks for this comprehensive response - and also for moving it!

A couple of clarifications/comments:
* FYI; date-sharding is not necessarily considered an "old" feature - there are definitely still valid use cases for this over partitioning.
* DBT Cloud doesn't show anything interesting if this is sharding - so 
* This is unfortunate here as my tables are not sharded - this is just part of our nomenclature (I won't describe our domain model as it is a little complex). It's even more unfortunate that sharding is implicit rather than explicit. Ideally DBT would be able to access some "is_sharded" property from either the BQ API or meta tables such as in information_schema. I think DBT here should expose an option to allow me to be explicit though so I can tell DBT that this is not sharded (is this a DBT thing or a DBT Cloud thing?).
* However, finally, in this particular case, this whole thing is a red herring because this table is not understood as sharded by BigQuery. Sharding has a suffix of `_YYYYMMDD`. In my case, it is a 14 digit number (which looks like `YYYYMMDDHHMMSS` but this is not important as it's not the sharding suffix) so perhaps DBT is using inconsistent logic here? Let me test...

Yep, you are right - a table _z shows up correctly. So DBT's pattern for detecting sharding is incorrect and should be updated to `_YYYYMMDD` (or perhaps `_\d{8}` is sufficient).

**Comment by adamcunnington-mlg** [comment]
Ah, I see the issue. The regex is flawed. You are missing the underscore separator. So you just match the last 8 digits of my 14 digit suffix and treat it like a shard.

DBT would also incorrectly think these are shards:
foo20220808
foo_bar20220808

**Comment by adamcunnington-mlg** [comment]
I've just stumbled across a related but separate issue: when the source is in a different BigQuery project (database), it doesn't link to the relation.

Take the example from this ticket - if I move one of those views to another database and add `database:` to the source configuration, DBT Cloud doesn't show the source as linked to a relation and thus doesn't pull back the information. My guess is the code from catalog.sql does not use the project from the source configuration but defaults to the project from the user's profile.

**Comment by jtcohen6** [comment]
@adamcunnington-mlg Thanks for the quick responses!
- It does sound like we should, at minimum, update the regex to more closely batch the BigQuery sharding suffix: `'^.+_[0-9]{8}$'`
- I agree it would be preferable to find out, from BigQuery directly, if a table is sharded. There's another PR (https://github.com/dbt-labs/dbt-bigquery/pull/238) proposing to move from `INFORMATION_SCHEMA.__TABLES__` to `INFORMATION_SCHEMA.TABLES`, but it doesn't look like it has any properties for identifying sharded tables ([docs](https://cloud.google.com/bigquery/docs/information-schema-tables)). In a world where dbt documented each relation one-by-one, rather than an entire database all together, it could be feasible to grab/pass this property.
- As for the last point: We should be running one "catalog" query per project/database. (The logic for that is [in `dbt-core` here](https://github.com/dbt-labs/dbt-core/blob/94a7cfa58df3df5d3b07b619c0510fead9195700/core/dbt/adapters/base/impl.py#L1012-L1048).) It's possible that this would fail to grab metadata on the other project's objects if dbt's user doesn't have permissions on that project, though. Are you able to see dbt running the metadata query in the debug-level logs?

**Comment by adamcunnington-mlg** [comment]
Thanks @jtcohen6 - agreed on tweaking regex.

BigQuery doesn't expose sharding explicitly so nothing you can do here - was just nice to have. I still think you could expose a per-table configuration parameter (`sources[].tables[].is_sharded`) to allow DBT developer to be explicit - but it's certainly very low priority / extreme edge case

Regarding the last bullet point, I'm not sure we're 100% on the same page. What i'm saying is I have a source from a different database - but DBT Cloud is not detecting the linked relation. My guess (and that's all it is) is that the code that builds the information required by the catalog, uses the BigQuery project ID of my user profile, NOT the `database` override i'm providing for the source. In other words, it's looking for schema information from the wrong project.

**Comment by adamcunnington-mlg** [comment]
What is the action on "separate bug report / investigation"? I imagine both of these things could be tackled in same, fairly-trivial PR? They're both making bug fixes to the catalog representation of source's relations.

Shout if you disagree and I can create a separate linked issue.

**Comment by jtcohen6** [comment]
I think that bug will be trickier to fix, if we can get a clear reproduction case. 

What should be happening: dbt runs that catalog query (SQL) _once per_ project/database, from the set of all `database` values you've configured on your dbt models, seeds, snapshots, and sources.

The process of collecting those `database` values, and orchestrating multiple queries to run, is defined in adapter methods (Python) across `dbt-bigquery` + the "base adapter" in `dbt-core`:
- `_get_catalog_schemas`[https://github.com/dbt-labs/dbt-bigquery/blob/9c36aa239fb674faebfadab0a2b6a38cd201da86/dbt/adapters/bigquery/impl.py#L684-L701] in `dbt-bigquery`
- [`_get_one_catalog`](https://github.com/dbt-labs/dbt-core/blob/94a7cfa58df3df5d3b07b619c0510fead9195700/core/dbt/adapters/base/impl.py#L1012-L1029)
- [`get_catalog`](https://github.com/dbt-labs/dbt-core/blob/94a7cfa58df3df5d3b07b619c0510fead9195700/core/dbt/adapters/base/impl.py#L1031-L1048)

If that catalog query isn't being run once for every database/project, it's the fault of those Python methods, not something we can fix within the SQL of the catalog query.
