### ISSUE TITLE
[CT-1032] `grant_access_to` only works reliably in single threaded mode

### ISSUE THREAD

**Issue by judahrand** [dbt-labs/dbt-bigquery#266]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Hey @judahrand, this is a documented limitation of `grant_access_to` in `dbt-bigquery`: https://docs.getdbt.com/reference/resource-configs/bigquery-configs#limitations

The main proposal for fixing this bug is to "batch up" all dataset access grants to the end of an invocation, similar to the discussion in https://github.com/dbt-labs/dbt-bigquery/issues/87#issuecomment-1157408966. I think that could be a reasonable approach—more efficient and single-threaded—at the cost of significant potential delay between when each view is (re)created, and when their access is authorized (all at once, after every model has run).

I'm going to close both of these issues in favor of a new one, just opened: https://github.com/dbt-labs/dbt-bigquery/issues/267

**Comment by judahrand** [comment]
@jtcohen6 Is there something inherently wrong with just locking around the changes (other than slowing it down) as in #265? Even if only a temporary fix it's surely better for it to work and be slow than just not work at all?

**Comment by jtcohen6** [comment]
@judahrand Fair! I called that out as an alternative in #267. I can reopen this bug as more narrowly scoped to just ensuring thread-safety.
