### ISSUE TITLE
[CT-1043] Support google-cloud-bigquery 3.x.x dependency

### ISSUE THREAD

**Issue by whittid4** [dbt-labs/dbt-bigquery#269]
### Describe the feature
`dbt-bigquery` requires a version of `google-cloud-bigquery` that is less than 3, but I have another dependency that has a minimum requirement of 3.2.0 and causing a conflict

```
dbt-bigquery (>=1.2.0,<2.0.0) requires google-cloud-bigquery (>=1.25.0,<3)
```

### Describe alternatives you've considered
No alternatives considered apart from not upgrading other dependencies that require `google-cloud-bigquery`

### Who will this benefit?
Anyone using `dbt-bigquery` along with other dependencies that require bigquery

### Are you interested in contributing this feature?
I would be happy to contribute to this unless there is a reason why the version has been pinned

**Comment by dbeatty10** [comment]
@whittid4 thanks for opening and we'd welcome a PR for this!

I think this is the last time the upper bounds were adjusted (before this adapter was migrated from `dbt-core` into its own `dbt-bigquery` repo):
- https://github.com/dbt-labs/dbt-core/pull/3156

Based on the discussion there, we'd welcome relaxing the upper bounds further:
- I didn't see any known incompatibilities discussed there.
- The upper bound of `<3` for `google-cloud-bigquery` was merged on 2021-04-02, but `google-cloud-bigquery` 3.0.0 wasn't released until [almost exactly a year later](https://pypi.org/project/google-cloud-bigquery/#history).

So this looks like an upper bound to protect against "unknowns" rather than "knowns".

Acceptance criteria:
- If all the tests pass after you relax the relevant upper bounds, then we should be clear for takeoff ✈️

**Comment by whittid4** [comment]
Thanks @dbeatty10, I will have a read through the contributing guide as I have not contributed to this repo before and try and get a PR up

**Comment by d-casal** [comment]
@dbeatty10 Hi Doug, one of our engineers (github eplus-aolalere) submitted a [PR for this issue](https://ghe.service.group/dti/dbt-bigquery-mirror/pull/1/files). Would you (or another maintainer on the team) be able to review the PR and see if it can progress? Thank you
