### ISSUE TITLE
[CT-1056] [bug] date_trunc macro on bigquery don't keep orginal format

### ISSUE THREAD

**Issue by cedric-orange** [dbt-labs/dbt-bigquery#272]
### Describe the bug
Macro date_trunc on bigquery use a convertion to timestamp, so result is in a timestamp format and not keep original format.

### Steps To Reproduce

Create a model with `date_trunc` macro usage, example :

```sql
{{ config(materialized='table') }}

with source_data as (
    select current_date() as day_date
    union all
    select null as day_date

)
select day_date, {{ date_trunc("month", "day_date") }} as month_date
from source_data
```

### Expected behavior

If source of date_trunc is a date format, output of this macro should be also a date format, and not a timestamp.

when reading adapter code https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/include/bigquery/macros/utils/date_trunc.sql it's normal to output a timestamp.

But date_trunc function exist on biguqery : https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions?hl=fr#date_trunc

Why don't use it ?

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.2.0 - Up to date!

Plugins:
  - bigquery: 1.2.0 - Up to date!
```

**Comment by dbeatty10** [comment]
Thanks for opening @cedric-orange!

## Background
[dbt's `date_trunc`](https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros#date_trunc) is intended for timestamp-y input rather than date input. The return type is also timestamp-y \*.

> \* Most databases have more than one data type for timestamps. For example, Snowflake has three! For sake of discussion, I'm just calling these "timestamp-y" data types so that I don't have to enumerate them all.

My belief is that [`timestamp_trunc`](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_trunc) was [used for BigQuery](https://github.com/dbt-labs/dbt-utils/blob/37199d3901a97e813899dc25c1f72601714c2c3c/macros/cross_db_utils/date_trunc.sql#L9-L12) in order to return BigQuery's `TIMESTAMP` data type rather than `DATE` since both [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/date_trunc.html) and [Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_DATE_TRUNC.html) return timestamp-y data types in their vendor specific `date_trunc` implementations. If the BigQuery adapter returned a date, but the other adapters returned some sort of timestamp, then the macro wouldn't be behaving consistently across dbt adapters, which is undesirable.

## Recommendation
If you expect both date input and output, there are a couple ways you can approach this:
1. Use the native `date_trunc` syntax for BigQuery directly rather than the dbt `{{ date_trunc(...) }}` implementation
1. Use the dbt `{{ date_trunc(...) }}` implementation but then downcast it to a date (caveat: I didn't test that this actually works)
1. Write a custom macro for your dbt project that implements the behavior you want. If you take this route and believe it's broadly useful, consider creating a [dbt package](https://docs.getdbt.com/docs/building-a-dbt-project/package-management) for the [dbt Hub](https://hub.getdbt.com/) or opening a pull request here for it to be considered for dbt-core.

## Resolution
Since there is a reasonable alternative, I'm going to close this. We can re-open if I overlooked some crucial consideration.
