### ISSUE TITLE
[CT-1059] Support the `location` option to create schema

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-bigquery#273]
### Describe the feature
BigQuery provides the `location` option to specify the location of a BigQuery dataset when creating a schema.

https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#schema_option_list

```
{{
  config(location="US")
}}
```

### Describe alternatives you've considered
We can already specify the default location with a dbt profile. But, 

### Additional context
NA

### Who will this benefit?
dbt users with BigQuery can deal with multiple locations of BigQuery datasets with a single dbt profile.

### Are you interested in contributing this feature?
I will work on it.

**Comment by jtcohen6** [comment]
(@dbeatty10 Picking this one up since I realize it's quite similar to https://github.com/dbt-labs/dbt-bigquery/issues/289, which I just triaged yesterday)

@yu-iskw If I understand right, the `location` property needs to be configured on the dataset (schema) when it is initially created. Specific tables within the same dataset cannot be configured with their own custom locations, right? (It looks like that's what https://github.com/dbt-labs/dbt-bigquery/pull/275 would do, by configuring at the table/model level.)

Two thoughts here:
1. As I outlined in https://github.com/dbt-labs/dbt-bigquery/issues/289#issuecomment-1237948296, it is now possible to reimplement dbt-bigquery's `create schema` behavior by implementing your own custom `create_schema` macro. However, there's no good way to supply schema-level configuration in dbt today. I just opened a `dbt-core` discussion to think more about this: https://github.com/dbt-labs/dbt-core/discussions/5781
2. My sense is that BigQuery does _not_ support cross-region querying, with the sole exception of copying datasets from one region to another. There are `location` options which are naturally multi-region, but in those cases you don't need to have different `location`. This is why we support `location` in the connection profile, to set the single location for use during the entire dbt invocation—whether a single- or multi-region location, it doesn't matter. Could you say more about the use case for configuring datasets with _different_ locations, within the _same_ project / invocation, given that limitation? Of course, it's possible that my understanding is incorrect or out of date!

**Comment by Fleid** [comment]
Hi @yu-iskw, 
I am closing this issue and the associated PR.

As @jtcohen6 sensed, it looks like moving data across locations in BigQuery is currently an EL thing, not a T thing. And dbt is all about that T. Please chime in if you feel this is not a fair assessment - or if the situation changes.
