### ISSUE TITLE
[CT-1140] [BUG] Integration Tests not cleaning up artifacts

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-bigquery#300]
### Describe the bug
[Integration test](https://github.com/dbt-labs/dbt-bigquery/blob/1.1.latest/tests/integration/docs_generate_tests/test_docs_generate.py) in branches 1.1 and 1.0 began failing after we exceeded the max number of allowed tables in our sandbox account for the `alternate_db` (project: dbt-test-alt). Once we dropped the old tables in that project the tests began to succeed again. 

Root cause is there are a few  (~5) tests where database objects aren't getting cleaned up after a run resulting in a steady accumulation. Since [we set a limit of 10k](https://github.com/dbt-labs/dbt-bigquery/blob/597aaa4667320a2f0e21abdf6ac10d523757183e/dbt/adapters/bigquery/impl.py#L260) on the number of objects to return when generating docs the tests fail since the created object is not in the catalog.json file docs generates.

Options:
1. Document this behavior and a script to clean up tables (minimum path forward)
2. Add better handling for cleaning up objects in alternate_db/dbt-test-alt
3. Update [dataset default table TTL](https://cloud.google.com/bigquery/docs/updating-datasets#table-expiration) so tables get automatically deleted

Option #1 is not satisfying but as this is not a frequent pain point (i.e. we will hit this issue maybe once a year) and is pretty easily fixed when it occurs this is not untenable.

### Steps To Reproduce
Run these tests until the number of tables exceeds 10k

### Expected behavior
Tests should clean up database objects. 

### Screenshots and log output
See:
* https://github.com/dbt-labs/dbt-bigquery/runs/8059670397?check_suite_focus=true#step:7:231

### System information
**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by McKnight-42** [comment]
tagging in a new conversion we are seeing also leaving artifacts post run: namely the new Alias tests
[dbt-core](https://github.com/dbt-labs/dbt-core/pull/5884)
[BigQuery](https://github.com/dbt-labs/dbt-bigquery/pull/318)

single test in bigquery leaving a model after run, was able to get a differnt model to stay after two different variations.
1. A model staying after changing database using` {"database": os.getenv("BIGQUERY_TEST_ALT_DATABASE")}`on a model which leaves a dataset in the alt database project.
2. Using `model_b": {"schema": unique_schema + "_alt"}` version of test from `dbt-core` by default leaving a dataset with an odd naming structure in the default `bigquery` project.

As we can see these hangups are around changes to schema in `bigquery` which means we may need to update pytest fixtures to have a step to verify against multiple databases rather than using `self.database` during our `drop_schema` calls
