### ISSUE TITLE
[CT-1854] [Bug] Incrementally materialized tables do not obey hours_to_expiration config

### ISSUE THREAD

**Issue by illiriks** [dbt-labs/dbt-bigquery#472]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After we moved some tables to incremental materialization, subsequent `dbt run`s did not set the expiration date to the current timestamp plus hours_to_expiration hours, causing our tables to expire. I took a look at the code and found that incremental materializations did not actually update the table options; the table options were only set on table or view creation.

![](https://user-images.githubusercontent.com/15371146/213318860-11af2fd1-7566-41f9-984a-1cc2520fca94.png)

### Expected Behavior

We would expect that the expiration date of the incrementally materialized table would be updated on each subsequent `dbt run` - not just on initial table creation. The docs [1] do not explicitly specify that this behavior is expected, but if it is, a note about this behavior would be helpful.

[1] https://docs.getdbt.com/reference/resource-configs/bigquery-configs#controlling-table-expiration

### Steps To Reproduce

In any environment, create an incrementally materialized table and set an hours_to_expiration config. `dbt run`, and note the expiration date is set properly. `dbt run` again; the expiration date is no longer updated

### Environment

```markdown
- OS: dbt Cloud, reproed on MacOS 12.3.9
- Python: unsure what version dbt Cloud uses, reproed on 3.9.15
- dbt-core: 1.3.2 on cloud, 1.3.1 locally
- dbt-bigquery: unknown on cloud, 1.3.0 locally
```

**Comment by dbeatty10** [comment]
Thanks for noticing this and reaching out @illiriks !

### Docs update
Agreed that a note about this behavior in the docs would be helpful. I opened up this PR to update the docs: https://github.com/dbt-labs/docs.getdbt.com/pull/2837

### Adding this as a new feature
I can totally see how this was unexpected from an end-user perspective. Since the original implementation is behaving as designed, I'd consider this a feature request rather than a bug though.

We don't have the capacity to prioritize implementing this, but we'd review a PR from a motivated community member that wanted to add the following type of logic during incremental runs:
```sql
ALTER TABLE mydataset.mytable
  SET OPTIONS (
    -- Sets table expiration to timestamp 2025-02-03 12:34:56
    expiration_timestamp = TIMESTAMP '2025-02-03 12:34:56');
```

Here's an example of getting this setting from the config:
- https://github.com/dbt-labs/dbt-bigquery/blob/3ce88d75ac78b9aac1dcaa184c94e235f661a6f0/dbt/adapters/bigquery/impl.py#L754-L755
