### ISSUE TITLE
[CT-2058] maximum_bytes_billed does not accept a value greater than int max (2147483647 bytes)

### ISSUE THREAD

**Issue by gunnava** [dbt-labs/dbt-bigquery#521]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

 
**Maximum bytes billed** - Limits the bytes billed for this query. If this query will have bytes billed beyond this limit, the query will be failed (without incurring a charge). If not specified, the bytes billed will be set to the project default.

The docs mention that the maximum_bytes_billed  parameter value should be supplied as an integer number of bytes: https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup however if one wants to set the limit to 20GB, it is not possible at the moment.  I have tested this at my end and found that this parameter is only taking values up to 2147483647 which is the int max value. Setting the limit to 20 GB is beyond the integer size threshold and hence fails.

maximum_bytes_billed is [defined as an int here](https://github.com/dbt-labs/dbt-bigquery/blob/edca37abfa21d492b75f1fa03d20e51da55304bb/dbt/adapters/bigquery/connections.py#L104) 

### Describe alternatives you've considered

NA

**Comment by maxQanalytics** [comment]
@gunnava Clearly describes the issue that we are encountering. We would like to set maximums to 100-1000GB. Primarily from a cost-concern standpoint.

**Comment by dbeatty10** [comment]
Thanks for opening @gunnava !

It certainly makes sense to be able to specify something larger than an int32 number of bytes! This is a bit surprising to me, because I expected `int` in Python 3 to be unbounded.

Could either you or @maxQanalytics share how you know larger values aren't working? Are both of you using dbt Core, or are either of you using dbt Cloud, by any chance?

e.g., are you seeing some kind of error output in your terminal or in your logs? Or is this setting just silently failing to take effect and allowing queries to run that are **larger** than the maximum you are trying to set?

I tried setting each of the following within my `profiles.yml`, and everything executed for me using Core: 1.4.1 and bigquery: 1.4.0:
- `maximum_bytes_billed: 1000000000000000`
- `maximum_bytes_billed: "{{ '1000000000000000' | as_number }}"`

But I'm using an extremely small table well under the int32 threshold you mentioned.

Are you using a hard-coded value for `maximum_bytes_billed` in profiles.yml? Or are you using [env_var()](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var)?

**Comment by dbeatty10** [comment]
@maxQanalytics Thanks for the screenshot and the full navigation path. Also, I'm impressed you and @gunnava were each able to find that you `int32` limit by trial and error 🧠

### The path forward
For dbt Cloud users, we have a dedicated support path described [here](https://docs.getdbt.com/guides/legacy/getting-help#dbt-cloud-support). I'm sorry for the hassle of re-directing you, but could you report this same error by using the speech bubble (💬) in the dbt Cloud interface or at [support@getdbt.com](mailto:support@getdbt.com)?

The things that will be most helpful to share with them:
1. Account Settings >> Projects >> Project Details >> Edit >> Connection Details >> Maximum Bytes Billed
2. The exact max value that worked for you, and the lowest value that didn't work.
3. You can also tell them that Doug Beatty from the Core team did some initial troubleshooting, and these values worked in Core.

In the meantime, I'm going to close this as `can't repro` _as it relates_ to dbt-bigquery and dbt-core, but please know we realize that this is something that still needs to be fixed (just not in **this** repository).
