### ISSUE TITLE
[CT-2136] [Bug] Null partitions fail to merge on insert_overwrite materialization strategy when using _dbt_max_partition

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-bigquery#544]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have seen a few reports recently of incremental `insert_overwrite` with `_dbt_max_partition` causing null partitions somehow. Which is itself, a separate issue, but the fact there are nulls causes the merge statement to fail:
Example: https://github.com/Velir/dbt-ga4/issues/128
```
21:43:49  Database Error in model fct_ga4__sessions_daily (models/marts/core/fct_ga4__sessions_daily.sql)
  Query error: Array cannot have a null element._field_1 at [76:46]
```

Other semi-related example: https://github.com/dbt-labs/dbt-bigquery/pull/285#issuecomment-1427137218

### Expected Behavior

partitions created / found without nulls
merge happens successfully

We can prevent the error by overwriting the lines in the `insert_overwrite` macro:
https://github.com/dbt-labs/dbt-bigquery/blob/a3d70544ab0cb736676c17932b8f52cd215fe1d7/dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql
 
changing lines 134-139 from:
``` 
     -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct {{ partition_by.render_wrapped() }})
          from {{ tmp_relation }}
      );
 ```
to:
```
      -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct {{ partition_by.render_wrapped() }} IGNORE NULLS)
          from {{ tmp_relation }}
      );
 ```

### Steps To Reproduce

I believe this creates the error:

in dbt Cloud, run the incremental twice in a row, -or- force it somehow to return no new rows. I think no new rows is creating a null partition

The `_dbt_max_partition` [does](https://github.com/dbt-labs/dbt-bigquery/blob/a3d70544ab0cb736676c17932b8f52cd215fe1d7/dbt/include/bigquery/macros/materializations/incremental_strategy/common.sql#L17) seem to remove nulls, but [this](https://github.com/dbt-labs/dbt-bigquery/blob/a3d70544ab0cb736676c17932b8f52cd215fe1d7/dbt/include/bigquery/macros/materializations/incremental_strategy/insert_overwrite.sql#L134-L138) does not:
```
      -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct {{ partition_by.render_wrapped() }})
          from {{ tmp_relation }}
```
causing the `array_agg` function to error out

### Relevant log output

```shell
See here: https://github.com/Velir/dbt-ga4/issues/128
```

### Environment

```markdown
- OS:
- Python:
- dbt-core:1.4.1
- dbt-bigquery:
```

**Comment by dbeatty10** [comment]
Thanks for a great write-up @patkearns10 !

It does sound like multiple people have reported the presence of null partitions:
- https://github.com/dbt-labs/dbt-bigquery/issues/319#issuecomment-1317776535
- https://github.com/dbt-labs/dbt-bigquery/pull/285#issuecomment-1427137218

Quoting from the latter gives a possible lead on how this is coming about:
> I noticed today a problem with a model I have added that sometimes has no new rows to add (on incremental runs) - the current merge SQL creates a `__NULL__` partition when there's no rows produced by the incremental source query.

### Proposed solution(s)
It seems like we could pursue a two-part solution:
1. Use your solution of adding `ignore nulls` to avoid the database error (this issue!)
2. Avoid creating a `__NULL__` partition in the first place (I don't know if we have a stand-alone issue for this yet)

#### Integration test
_Ideally_, we'd add an integration test that does the following:
1. Creates a `__NULL__` partition
1. Includes an incremental model like [this](https://github.com/Velir/dbt-ga4/blob/5e7a71bf0862e078b17aaf7f47d1063fd311487e/models/marts/core/fct_ga4__sessions_daily.sql) that fails due to the `__NULL__` partition

This integration should fail without @patkearns10's fix, but it should succeed when including the fix. 

### Workaround, in the meantime
Here's a full description of the workaround:
https://github.com/Velir/dbt-ga4/issues/128#issuecomment-1433885044

**Comment by Fleid** [comment]
@dbeatty10 good point on the new, separate issue. It's #553

**Comment by VersusFacit** [comment]
Just leaving for the record that I spent several hours trying different combinations to trigger this behavior with no luck. At least on the command line, I can't get this reported behavior to surface. In particular, if we can't get this surfaced using a non-cloud CI, then we can't test the feature. Obviously, that's concerning.

**Comment by dgitis** [comment]
I've been watching this issue after being pointed here when I uncovered this issue in a package that I contribute to. @VersusFacit  I was also unable to recreate [the package issue that I reported](https://github.com/Velir/dbt-ga4/issues/128) in a non-cloud environment.
