### ISSUE TITLE
`UPDATE` operation is missing a useful AdapterResponse

### ISSUE THREAD

**Issue by rjh336** [dbt-labs/dbt-bigquery#68]
### Describe the bug
When calling load_result() from a statement block connecting to a bigquery db, if the query is an UPDATE operation, we do not get an AdapterResponse on par with other DML operations.

Seems like it should be included here: https://github.com/dbt-labs/dbt-bigquery/blob/95ca84b5100c2b940751d8a65aaeb914df211ac7/dbt/adapters/bigquery/connections.py#L417

Moreover, what is the reason that `SELECT` statements do not also get a filled out AdapterResponse?

### Steps To Reproduce
```
{% macro test_response_object() %}
{% call statement('test') %}
... UPDATE STATEMENT ...
{% endcall %}
{% set result = load_result('test') %}
{{ dbt_utils.log_info(result) }}
{% endmacro %}
```
From the command line:
`dbt run-operation test_response_object`

Result:
```
{'response': BigQueryAdapterResponse(_message='OK', code=None, rows_affected=None, bytes_processed=None), 'data': [], 'table': <agate.table.Table object at 0x114f1cd90>}
```

### Expected behavior
BigQueryAdapterResponse field should be populated with values reported by the BigQuery API. Here is an example of what you get when you run a DELETE:
```
{'response': BigQueryAdapterResponse(_message='DELETE (1.0 rows, 352.5 KB processed)', code='DELETE', rows_affected=1, bytes_processed=360929), 'data': [], 'table': <agate.table.Table object at 0x1065e82b0>}
```

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - bigquery: 0.21.0
  - snowflake: 0.21.0
  - redshift: 0.21.0
  - postgres: 0.21.0
```

**The operating system you're using:**
macOS v 11.6 (20G165)

**The output of `python --version`:**
`Python 3.8.11`

**Comment by jtcohen6** [comment]
@rjh336 Thanks for opening the issue!

The reason these values are missing for `SELECT` + `UPDATE` statements is because we don't have logic to handle those statement types within `execute`:

https://github.com/dbt-labs/dbt-bigquery/blob/95ca84b5100c2b940751d8a65aaeb914df211ac7/dbt/adapters/bigquery/connections.py#L393-L432

We totally could! From a little poking around, I think:
- `UPDATE` should be a simple addition to the conditional branch that includes `['INSERT', 'DELETE', 'MERGE']`
- `SELECT` needs its own new conditional branch, which might look something like:
```python
        elif query_job.statement_type == 'SELECT':
            code = 'SELECT'
            bytes_processed = query_job.total_bytes_processed
            
            # these are internal properties, so we should be cautious
            # maybe more trouble than it's worth?
            if (
                hasattr(query_job, '_query_results') 
                and hasattr(query_job._query_results, '_properties')
                and hasattr(query_job._query_results._properties, 'get')
            ):
                num_rows = query_job._query_results._properties.get('totalRows')
```

I'm going to mark this a `good first issue`, and I'd welcome a PR to add those in :)
